all:
	g++ -g -o radxops  -lnetcdf -lNcxx -lhdf5_cpp -lRadx  radxops.cc
	g++ -g -o radxops_DUG  -lnetcdf -lNcxx -lhdf5_cpp -lRadx  radxops_DUG.cc
	g++ -g -o radxmodel  -lnetcdf -lNcxx -lhdf5_cpp -lRadx  radxmodel.cc
